import { createFileRoute } from "@tanstack/react-router";
import { useRef, useState, useEffect, useCallback } from "react";
import {
  ScanLine,
  CornerDownLeft,
  RotateCcw,
  Volume2,
  Sparkles,
  Check,
  AlertCircle,
  ArrowUpRight,
} from "lucide-react";
import { AppShell } from "@/components/whitfield/app-shell";
import { PageHeader, Button, StatusPill, Panel } from "@/components/whitfield/primitives";
import { getProductByUpcApi, getProductBySkuApi, getProductsApi } from "@/api/products";
import { getInventoryApi, adjustInventoryApi } from "@/api/inventory";
import { Product, Inventory, WarehouseId } from "@/types/wms";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { useAuth } from "@/auth/auth-context";
import { useQuery } from "@tanstack/react-query";

export const Route = createFileRoute("/scanner")({
  head: () => ({
    meta: [
      { title: "Barcode Scanner — Whitfield Fulfillment" },
      {
        name: "description",
        content:
          "High-speed barcode scanner console with keyboard wedge auto-focus, leading-zero UPC padding, and tactile inventory adjustments.",
      },
    ],
  }),
  component: ScannerPage,
});

type Phase = "idle" | "resolving" | "found" | "notfound";

// Web Audio API feedback beeps
function playFeedbackAudio(success: boolean) {
  try {
    const AudioContext = window.AudioContext || (window as any).webkitAudioContext;
    if (!AudioContext) return;
    const ctx = new AudioContext();
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();
    osc.connect(gain);
    gain.connect(ctx.destination);

    if (success) {
      osc.type = "sine";
      osc.frequency.setValueAtTime(880, ctx.currentTime); // A5 note
      gain.gain.setValueAtTime(0.12, ctx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.12);
      osc.start();
      osc.stop(ctx.currentTime + 0.12);
    } else {
      osc.type = "sawtooth";
      osc.frequency.setValueAtTime(220, ctx.currentTime);
      gain.gain.setValueAtTime(0.15, ctx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.25);
      osc.start();
      osc.stop(ctx.currentTime + 0.25);
    }
  } catch (e) {
    // Audio context may be muted or blocked by browser policy
  }
}

function ScannerPage() {
  const { hasPermission } = useAuth();
  const canAdjust = hasPermission("inventory:adjust");

  const [value, setValue] = useState("");
  const [phase, setPhase] = useState<Phase>("idle");
  const [product, setProduct] = useState<Product | null>(null);
  const [inventoryList, setInventoryList] = useState<Inventory[]>([]);
  const [scanStats, setScanStats] = useState({ scans: 0, resolved: 0, mismatches: 0 });

  const inputRef = useRef<HTMLInputElement>(null);

  // Fetch product master catalog for quick demo test tags
  const { data: catalog = [] } = useQuery({
    queryKey: ["products"],
    queryFn: getProductsApi,
  });

  // Ensure keyboard wedge scanner always has focus
  useEffect(() => {
    inputRef.current?.focus();
  }, [phase]);

  const resolveBarcodeOrSku = useCallback(async (codeToScan: string) => {
    const rawCode = codeToScan.trim();
    if (!rawCode) return;

    setPhase("resolving");
    setScanStats((prev) => ({ ...prev, scans: prev.scans + 1 }));

    // Clean leading/trailing quotes often generated by barcode guns
    const cleanCode = rawCode.replace(/['"]+/g, "");

    // Auto-pad leading zeros for standard UPC/GTIN formats if stripped
    const paddedUpc12 = cleanCode.padStart(12, "0");
    const paddedUpc13 = cleanCode.padStart(13, "0");

    try {
      let foundProd: Product | null = null;

      // 1. Try exact UPC
      try {
        foundProd = await getProductByUpcApi(cleanCode);
      } catch {
        // 2. Try 12-digit padded UPC
        try {
          foundProd = await getProductByUpcApi(paddedUpc12);
        } catch {
          // 3. Try 13-digit padded EAN
          try {
            foundProd = await getProductByUpcApi(paddedUpc13);
          } catch {
            // 4. Try exact SKU
            try {
              foundProd = await getProductBySkuApi(cleanCode);
            } catch {
              // 5. Try uppercase/formatted SKU
              try {
                const skuFormatted = cleanCode.toUpperCase().startsWith("SKU-")
                  ? cleanCode.toUpperCase()
                  : `SKU-${cleanCode.toUpperCase()}`;
                foundProd = await getProductBySkuApi(skuFormatted);
              } catch {
                foundProd = null;
              }
            }
          }
        }
      }

      if (foundProd) {
        setProduct(foundProd);
        const inv = await getInventoryApi({ product_id: foundProd.product_id });
        setInventoryList(inv);
        setPhase("found");
        setScanStats((prev) => ({ ...prev, resolved: prev.resolved + 1 }));
        playFeedbackAudio(true);
        toast.success(`Resolved ${foundProd.sku}: ${foundProd.name}`);
      } else {
        setProduct(null);
        setInventoryList([]);
        setPhase("notfound");
        setScanStats((prev) => ({ ...prev, mismatches: prev.mismatches + 1 }));
        playFeedbackAudio(false);
        toast.error(`No product matches barcode ${rawCode}`);
      }
    } catch (err: any) {
      setProduct(null);
      setInventoryList([]);
      setPhase("notfound");
      setScanStats((prev) => ({ ...prev, mismatches: prev.mismatches + 1 }));
      playFeedbackAudio(false);
    }
  }, []);

  const submit = (e: React.FormEvent) => {
    e.preventDefault();
    resolveBarcodeOrSku(value);
  };

  const reset = () => {
    setValue("");
    setProduct(null);
    setInventoryList([]);
    setPhase("idle");
    inputRef.current?.focus();
  };

  const handleQuickAdjust = async (warehouseId: WarehouseId, quantityDelta: number) => {
    if (!product) return;
    try {
      await adjustInventoryApi({
        warehouse_id: warehouseId,
        product_id: product.product_id,
        quantity_delta: quantityDelta,
        reason: "Scanner quick count update",
      });
      toast.success(
        `Updated ${warehouseId} stock by ${quantityDelta > 0 ? "+" : ""}${quantityDelta}`,
      );
      const updatedInv = await getInventoryApi({ product_id: product.product_id });
      setInventoryList(updatedInv);
      playFeedbackAudio(true);
    } catch (err: any) {
      toast.error(err.message || "Failed to adjust inventory.");
      playFeedbackAudio(false);
    }
  };

  const renoData = inventoryList.find((i) => i.warehouse_id === "RENO") || {
    quantity_available: 0,
    quantity_reserved: 0,
  };
  const columbusData = inventoryList.find((i) => i.warehouse_id === "COLUMBUS") || {
    quantity_available: 0,
    quantity_reserved: 0,
  };

  return (
    <AppShell>
      <PageHeader
        eyebrow="Operations"
        title="Barcode Scanner"
        description="High-speed barcode scanner console with keyboard wedge auto-focus, leading-zero UPC padding, and tactile inventory adjustments."
        actions={
          <Button onClick={reset} variant="ghost">
            <RotateCcw className="size-4 mr-1.5" /> Reset
          </Button>
        }
      />

      <div className="grid gap-6 lg:grid-cols-[minmax(0,420px)_1fr]">
        {/* Scan console */}
        <section className="panel relative overflow-hidden space-y-4">
          <div className="border-b border-border px-5 py-4 flex items-center justify-between">
            <p className="eyebrow">Scanner Console</p>
            <span className="text-[10px] font-mono text-muted-foreground uppercase">
              Keyboard Wedge Auto-Focus
            </span>
          </div>

          <div className="px-5 pb-6">
            {/* Visual Barcode Graphic */}
            <div className="relative mx-auto flex h-28 w-full max-w-[280px] items-center justify-center overflow-hidden rounded-xl border border-border-strong bg-surface-2 shadow-inner">
              <div className="flex h-14 items-end gap-[3px]">
                {Array.from({ length: 32 }).map((_, i) => (
                  <span
                    key={i}
                    className="w-[3px] rounded-xs bg-foreground/80"
                    style={{ height: `${40 + ((i * 37) % 55)}%` }}
                  />
                ))}
              </div>
              {phase === "resolving" ? (
                <span className="scan-sweep absolute inset-x-0 h-10 bg-linear-to-b from-transparent via-signal/40 to-transparent animate-pulse" />
              ) : null}
              <span
                className={cn(
                  "absolute inset-0 transition-colors duration-300 pointer-events-none",
                  phase === "found" && "bg-ok/10",
                  phase === "notfound" && "bg-danger/10",
                )}
              />
            </div>

            {/* Input Form */}
            <form onSubmit={submit} className="mt-5">
              <div className="relative">
                <ScanLine className="absolute top-1/2 left-3.5 size-4 -translate-y-1/2 text-muted-foreground" />
                <input
                  ref={inputRef}
                  value={value}
                  onChange={(e) => {
                    setValue(e.target.value);
                    if (phase !== "idle") setPhase("idle");
                  }}
                  placeholder="Scan or enter UPC / SKU..."
                  autoFocus
                  className="numeric h-12 w-full rounded-xl border border-border bg-surface pr-10 pl-10 text-sm tracking-[0.08em] transition-colors focus:border-signal focus:ring-2 focus:ring-signal/20 focus:outline-none"
                />
                <button
                  type="submit"
                  className="absolute top-1/2 right-3 -translate-y-1/2 text-muted-foreground hover:text-signal transition-colors cursor-pointer"
                >
                  <CornerDownLeft className="size-4" />
                </button>
              </div>
            </form>

            <div className="mt-3.5 flex items-center justify-between">
              <div className="flex items-center gap-2">
                {phase === "idle" ? (
                  <StatusPill tone="neutral">
                    <span className="pulse-dot">Ready to scan</span>
                  </StatusPill>
                ) : null}
                {phase === "resolving" ? (
                  <StatusPill tone="signal">Resolving live API...</StatusPill>
                ) : null}
                {phase === "found" ? <StatusPill tone="ok">Product resolved</StatusPill> : null}
                {phase === "notfound" ? <StatusPill tone="danger">No match</StatusPill> : null}
              </div>

              <span className="text-[11px] font-mono text-muted-foreground">
                {scanStats.scans} scan{scanStats.scans === 1 ? "" : "s"}
              </span>
            </div>

            {/* Quick Demo Tags */}
            {catalog.length > 0 && (
              <div className="mt-6 pt-4 border-t border-border space-y-2">
                <p className="text-[11px] font-mono text-muted-foreground uppercase tracking-wider">
                  Quick Demo Scan:
                </p>
                <div className="flex flex-wrap gap-1.5">
                  {catalog.slice(0, 4).map((p) => (
                    <button
                      key={p.product_id}
                      type="button"
                      onClick={() => {
                        setValue(p.upc || p.sku);
                        resolveBarcodeOrSku(p.upc || p.sku);
                      }}
                      className="rounded-md border border-border bg-surface-2 px-2.5 py-1 text-xs text-foreground/80 hover:text-foreground hover:border-signal transition-colors font-mono cursor-pointer"
                    >
                      {p.sku}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>
        </section>

        {/* Result Area */}
        <section className="min-h-[320px]">
          {phase === "found" && product ? (
            <div key={product.product_id} className="anim-rise panel overflow-hidden shadow-xs">
              <div className="flex items-start justify-between gap-4 border-b border-border px-6 py-5 bg-surface-2/30">
                <div>
                  <p className="eyebrow text-signal">Product Matched</p>
                  <h2 className="mt-1.5 text-2xl font-semibold tracking-tight text-foreground">
                    {product.name}
                  </h2>
                  <p className="numeric mt-1.5 text-xs text-muted-foreground">
                    SKU: <span className="font-semibold text-foreground">{product.sku}</span> · UPC:{" "}
                    <span className="font-mono text-foreground">{product.upc}</span> · Reorder
                    Point: {product.reorder_point} units
                  </p>
                </div>
                <StatusPill tone="ok">Verified Live</StatusPill>
              </div>

              <div className="grid sm:grid-cols-2">
                {[
                  { name: "RENO" as WarehouseId, data: renoData },
                  { name: "COLUMBUS" as WarehouseId, data: columbusData },
                ].map((w, i) => (
                  <div
                    key={w.name}
                    className={cn(
                      "px-6 py-6",
                      i === 0 ? "border-b border-border sm:border-r sm:border-b-0" : "",
                    )}
                  >
                    <div className="flex items-center justify-between">
                      <p className="numeric text-xs font-semibold tracking-wider text-muted-foreground uppercase">
                        {w.name} HUB
                      </p>
                    </div>

                    <div className="mt-4 flex items-end gap-8">
                      <div>
                        <div className="numeric text-4xl leading-none font-semibold text-foreground">
                          {w.data.quantity_available.toLocaleString()}
                        </div>
                        <div className="mt-2 text-xs text-muted-foreground">available units</div>
                      </div>
                      <div>
                        <div className="numeric text-4xl leading-none font-semibold text-muted-foreground">
                          {w.data.quantity_reserved.toLocaleString()}
                        </div>
                        <div className="mt-2 text-xs text-muted-foreground">reserved</div>
                      </div>
                    </div>

                    {canAdjust ? (
                      <div className="mt-6 flex gap-2">
                        <Button size="sm" onClick={() => handleQuickAdjust(w.name, 10)}>
                          +10 Quick Count
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleQuickAdjust(w.name, -1)}
                        >
                          -1 Count
                        </Button>
                      </div>
                    ) : null}
                  </div>
                ))}
              </div>
            </div>
          ) : null}

          {phase === "notfound" ? (
            <div className="anim-rise panel flex flex-col items-center justify-center px-6 py-20 text-center">
              <div className="grid size-12 place-items-center rounded-2xl bg-danger/10 text-danger mb-3">
                <AlertCircle className="size-6" />
              </div>
              <p className="eyebrow text-danger">Unresolved Barcode</p>
              <h2 className="mt-2 text-lg font-semibold text-foreground">
                No product record matched that barcode
              </h2>
              <p className="mt-1.5 max-w-sm text-xs text-muted-foreground">
                Ensure the UPC label is clean, confirm leading zero padding, or register the item in
                the master catalog.
              </p>
              <div className="mt-5 flex gap-2">
                <Button onClick={reset}>Scan another</Button>
              </div>
            </div>
          ) : null}

          {phase === "idle" || phase === "resolving" ? (
            <Panel title="Scanner Activity" meta="Live Shift Telemetry">
              <div className="grid grid-cols-3 divide-x divide-border">
                {[
                  [String(scanStats.scans), "Total Scans"],
                  [String(scanStats.resolved), "Resolved"],
                  [String(scanStats.mismatches), "Mismatches"],
                ].map(([v, l]) => (
                  <div key={l} className="px-5 py-6">
                    <div className="numeric text-2xl leading-none font-semibold">{v}</div>
                    <div className="mt-2 text-xs text-muted-foreground">{l}</div>
                  </div>
                ))}
              </div>
              <div className="border-t border-border px-5 py-4 flex items-center justify-between text-xs text-muted-foreground">
                <span>Handheld USB/Bluetooth scanners supported</span>
                <span className="font-mono text-[11px] text-ok flex items-center gap-1">
                  <Check className="size-3.5" /> Fast Wedge Active
                </span>
              </div>
            </Panel>
          ) : null}
        </section>
      </div>
    </AppShell>
  );
}
